version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config-service:
    environment:
      CONFIG_PATH: config-files
    build:
      context: ./config-service
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  discovery-service:
    build:
      context: ./discovery-service
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8762:8762
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  gateway-service:
    build:
      context: ./gateway-service
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  device-service:
    build:
      context: ./device-service
      dockerfile: Dockerfile_dev
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8082:8082
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  price-service:
    build:
      context: ./price-service
      dockerfile: Dockerfile_dev
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8083:8083
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  shop-service:
    build:
      context: ./shop-service
      dockerfile: Dockerfile_dev
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8081:8081
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  monitoring:
    build:
      context: ./monitor-service
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"