version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 5671:5671
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"

  config-service:
    environment:
      CONFIG_PATH: config-files
#      CONFIG_SERVICE_URL: ${CONFIG_SERVICE_URL}
#      DISCOVERY_SERVICE_URL: ${DISCOVERY_SERVICE_URL}
    build:
      context: ./config-service
    ports:
      - 8888:8888
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"

  discovery-service:
    build:
      context: ./discovery-service
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - 8762:8762
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"


  gateway-service:
    build:
      context: ./gateway-service
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - 8081:8081
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"

  device-service:
    build:
      context: ./device-service
    depends_on:
      discovery-service:
        condition: service_healthy
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"

  price-service:
    build:
      context: ./price-service
    depends_on:
      discovery-service:
        condition: service_healthy
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"

  shop-service:
    build:
      context: ./shop-service
    depends_on:
      discovery-service:
        condition: service_healthy
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"


#  monitor-service:
#    build:
#      context: ./monitor-service
#    depends_on:
#      discovery-service:
#        condition: service_healthy
#    ports:
#      - 8080:8080
#      - 8989:8989
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "10"
