version: '2.1'
services:
  config-service:
    environment:
      DISCOVERY_SERVICE_URL: http://10.23.9.122:8762/eureka
    build:
      context: ./config-service
    ports:
      - 8888:8888

  discovery-service:
    environment:
      CONFIG_SERVICE_URL: http://10.23.9.122:8888
    build:
      context: ./discovery-service
    depends_on:
      - config-service
    ports:
      - 8762:8762


  gateway-service:
    build:
      context: ./gateway-service
    depends_on:
      - config-service
      - discovery-service
    ports:
      - 8080:8080

  device-service:
    build:
      context: ./device-service
    depends_on:
      - config-service
      - discovery-service

  price-service:
    build:
      context: ./price-service
    depends_on:
      - config-service
      - discovery-service

  shop-service:
    build:
      context: ./shop-service
    depends_on:
      - config-service
      - discovery-service

