FROM java:8-jre
MAINTAINER Artem

ADD ./build/libs/device-service-0.0.1-SNAPSHOT.jar /app.jar
CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8082",  "-Xmx200m", "-jar", "/app.jar"]

EXPOSE 8082